version: '3.8'
services:
  api:
    build: .
    container_name: chat-app-api
    ports:
      - '4000:4000'
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./:/usr/src/app
    command: npm run dev
  mongo:
    image: mongo:6
    container_name: chat-app-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    ports:
      - '6379:6379'
volumes:
  mongo-data:
    driver: local
